#崩溃时是否自动重启
CrashAutoRestart = true

#是否加载 MCBS\DllAppComponents\ 文件夹中的DLL应用程序
#支持的文件类型: 程序集.dll
LoadDllAppComponents = false

BuildColorMappingCaches = [-3]

#系统服务AppID
ServicesAppID = "Services"

#启动项AppID列表
StartupChecklist = [
    "Desktop"
]